version: "3.9"
services:
  api-node:
    image: api-node-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
    ports:
      - 3000:3000
    restart: unless-stopped